Fixed compile error under MSVC 2015
In init list of constructor_wrapper
"m_param_info_list(create_paramter_info_array(m_param_infos))"
I retrieved a fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1421)
The reason is MSVC 2015 cannot handle sizeof...(),
MSVC 2013 could handle it...